apiVersion: networking.k8s.io/v1   # Specifies the API version for the Ingress resource
kind: Ingress
metadata:
  name: ${INGRESS_RULE_NAME}       # substitutable name, support blue-green
  namespace: ${STAGE}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"  # Use regex matching in paths
    kubernetes.io/ingress.class: nginx             # Select the NGINX Ingress controller
    # Setup Cookie Affinity
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "JSESSIONID"
    nginx.ingress.kubernetes.io/session-cookie-path: "/"

spec:
  ingressClassName: nginx          # Use nginx as IngressController
  rules:                           # Defines the routing rules for HTTP traffic
    - host: ${SUB_DOMAIN}.tiansiwork.live
      http:
        paths:
          # APP: path start from "/api"
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: app-service-${APP_VERSION}
                port:
                  number: 8080

          # FRONTEND: path start from "/"
          - path: /                    # Match all requests starting with "/"
            pathType: Prefix           # Use prefix matching for path ("/" matches everything)
            backend:                   # Defines where to send matching traffic
              service:
                name: frontend-service-${FRONTEND_VERSION} # Name of the Service (ClusterIP) to route traffic to
                port:
                  number: 80         # The port exposed by the Service
